spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_javaee?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  redis:
    # redis服务器地址
    host: 192.168.238.130
    # redis服务器端口
    port: 6379
    # redis服务器密码
    password: root
    # 选择哪个数据库，默认0库
    database: 0
    # 连接超时时间
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数，默认8
        max-active: 1024
        # 最大连接阻塞等待时间，单位为毫秒，默认-1ms
        max-wait: 10000ms
        # 最大空闲连接，默认8
        max-idle: 200
        # 最小空闲连接，默认0
        min-idle: 5

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    db-config:
      # 表前缀
      table-prefix: sys_
      # 主键自增
      id-type: AUTO
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# SQL打印(方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
    com.hexiang.springSecuruty.mapper: debug